# Generated by Django 3.2.3 on 2021-05-23 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, max_digits=64)),
                ('bidder', models.ManyToManyField(related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('author', models.ManyToManyField(related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ManyToManyField(related_name='comments', to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ManyToManyField(related_name='bids', to='auctions.Listing'),
        ),
    ]
