# Generated by Django 3.2.3 on 2021-05-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210523_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='start_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64),
        ),
    ]
